# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
    desc: Show this help.

  build:
    cmds:
      - go build -o ~/Bin/multipass-compose ./cmd/multipass-compose/main.go
    desc: Build the go binary.

  test:
    cmds:
      - go test -v -count=1 ./...
    desc: Run unit tests.

  test/integration:
    cmds:
      - bats --timing .
    dir: t/bats
    desc: Run integration tests.

  docs/run:
    cmds:
      - docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
    desc: Run docs locally in docker
